import os
from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Data directory can be relocated (e.g. a mounted volume in containers) via
# the ALFCHAMPS_DATA_DIR env var. Defaults to ./data relative to the repo root.
DATA_DIR = Path(os.environ.get("ALFCHAMPS_DATA_DIR", BASE_DIR / "data"))
UPLOAD_DIR = DATA_DIR / "uploads"
REPORTS_DIR = DATA_DIR / "reports"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=BASE_DIR / ".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    app_name: str = "Alfchamps"
    app_version: str = "1.0.0"
    environment: str = "development"

    database_url: str = f"sqlite:///{(DATA_DIR / 'alfchamps.db').as_posix()}"
    cors_origins: str = "http://localhost:5173,http://127.0.0.1:5173"

    upload_max_size_mb: int = 10
    allowed_upload_extensions: str = "png,jpg,jpeg,webp,gif"

    report_title_default: str = "Security Assessment Report"
    report_footer: str = "Generated by Alfchamps"


    @property
    def cors_origin_list(self) -> list[str]:
        return [o.strip() for o in self.cors_origins.split(",") if o.strip()]

    @property
    def allowed_extensions(self) -> set[str]:
        return {e.strip().lower() for e in self.allowed_upload_extensions.split(",") if e.strip()}

    @property
    def upload_dir(self) -> Path:
        return UPLOAD_DIR

    @property
    def reports_dir(self) -> Path:
        return REPORTS_DIR

    def ensure_dirs(self) -> None:
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)


@lru_cache
def get_settings() -> Settings:
    settings = Settings()
    settings.ensure_dirs()
    return settings
